# Generated by Django 6.1.1 on 2026-10-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='nombre_eps',
            field=models.CharField(blank=True, choices=[('Aliansalud EPS', 'Aliansalud EPS'), ('Anas Wayuu EPSI', 'Anas Wayuu EPSI'), ('Asmet Salud', 'Asmet Salud'), ('Asociación Indígena del Cauca EPSI', 'Asociación Indígena del Cauca EPSI'), ('Cajacopi Atlántico', 'Cajacopi Atlántico'), ('Capital Salud', 'Capital Salud'), ('Capresoca', 'Capresoca'), ('Comfachocó', 'Comfachocó'), ('Comfaoriente', 'Comfaoriente'), ('Comfenalco Valle', 'Comfenalco Valle'), ('Compensar EPS', 'Compensar EPS'), ('Coosalud EPS', 'Coosalud EPS'), ('Dusakawi EPSI', 'Dusakawi EPSI'), ('Emssanar', 'Emssanar'), ('EPM - Empresas Públicas de Medellín', 'EPM - Empresas Públicas de Medellín'), ('EPS Familiar de Colombia', 'EPS Familiar de Colombia'), ('EPS Sanitas', 'EPS Sanitas'), ('EPS Sura', 'EPS Sura'), ('Famisanar', 'Famisanar'), ('Fondo de Pasivo Social de Ferrocarriles Nacionales', 'Fondo de Pasivo Social de Ferrocarriles Nacionales'), ('Mallamas EPSI', 'Mallamas EPSI'), ('Mutual Ser', 'Mutual Ser'), ('Nueva EPS', 'Nueva EPS'), ('Pijaos Salud EPSI', 'Pijaos Salud EPSI'), ('Salud Bolívar EPS', 'Salud Bolívar EPS'), ('Salud Mía', 'Salud Mía'), ('Salud Total EPS', 'Salud Total EPS'), ('Savia Salud', 'Savia Salud'), ('SOS - Servicio Occidental de Salud', 'SOS - Servicio Occidental de Salud')], max_length=100, verbose_name='Nombre de la EPS'),
        ),
    ]
