# Generated by Django 6.1.1 on 2026-10-07 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('pacientes', '0002_alter_paciente_nombre_eps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateTimeField(verbose_name='Fecha de la consulta')),
                ('motivo', models.CharField(max_length=300, verbose_name='Motivo de consulta')),
                ('sintomas', models.TextField(blank=True, verbose_name='Síntomas / anamnesis')),
                ('tratamiento', models.TextField(blank=True, verbose_name='Tratamiento / indicaciones')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('enfermedades', models.ManyToManyField(blank=True, related_name='consultas', to='catalogos.enfermedad', verbose_name='Diagnósticos (enfermedades)')),
                ('medicamentos', models.ManyToManyField(blank=True, related_name='consultas', to='catalogos.medicamento', verbose_name='Medicamentos recetados')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Médico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Consulta médica',
                'verbose_name_plural': 'Consultas médicas',
                'ordering': ['-fecha_consulta'],
            },
        ),
    ]
